include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = EtoileUITests

ADDITIONAL_INCLUDE_DIRS += -I../

EtoileUITests_OBJC_FILES = \
	test_ETLayoutItem.m \
	test_ETLayoutItemBuilder.m \
	test_ETPickboard.m \
	test_ETContainer.m \
	test_ETController.m \
	test_ETView.m \
	test_ETLayout.m

include $(GNUSTEP_MAKEFILES)/subproject.make
