include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = EtoileUITests

EtoileUITests_OBJC_FILES = \
	test_ETLayoutItem.m \
	test_ETLayoutItemBuilder.m \
	test_ETPickboard.m \
	test_ETContainer.m \
	test_ETView.m

include $(GNUSTEP_MAKEFILES)/subproject.make
