include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = libEtoileUI

ADDITIONAL_OBJCFLAGS = 
libEtoileUI_OBJCFLAGS += -std=c99

libEtoileUI_OBJC_FILES = \
	Controls+Etoile.m \
	ETApplication.m \
	ETBrowserLayout.m \
	ETComputedLayout.m \
	ETController.m \
	ETContainer+EventHandling.m \
	ETContainer.m \
	ETContainers.m \
	ETDecoratorItem.m \
	ETEvent.m \
	ETFlowLayout.m \
	ETFreeLayout.m \
	ETGeometry.m \
	ETInspector.m \
	ETLayer.m \
	ETLayoutItemBuilder.m \
	ETLayoutItem+Events.m \
	ETLayoutItem+Factory.m \
	ETLayoutItemGroup.m \
	ETLayoutItemGroup+Mutation.m \
	ETLayoutItem.m \
	ETLayoutItem+Reflection.m \
	ETLayoutItem+Scrollable.m \
	ETLayoutLine.m \
	ETLayout.m \
	ETLineLayout.m \
	ETObjectBrowserLayout.m \
	ETOutlineLayout.m \
	ETPaneLayout.m \
	ETPaneSwitcherLayout.m \
	ETPersistencyController.m \
	ETPickboard.m \
	ETScrollableAreaItem.m \
	ETShape.m \
	ETStackLayout.m \
	ETStyle.m \
	ETStyleGroup.m \
	ETStyleRenderer.m \
	ETTableLayout.m \
	ETTextEditorLayout.m \
	ETUIItem.m \
	ETUIItemFactory.m \
	ETView.m \
	ETViewModelLayout.m \
	ETWidgetLayout.m \
	ETWindowItem.m \
	FSBrowserCell.m \
	NSImage+Etoile.m \
	NSObject+EtoileUI.m \
	NSView+Etoile.m \
	NSWindow+Etoile.m

libEtoileUI_OBJC_FILES += \
	UKPluginsRegistry+Icons.m \
	NSBezierPathCappedBoxes.m \
	NSImage+NiceScaling.m \
	UKNibOwner.m

libEtoileUI_OBJC_FILES += \
	ETEventProcessor.m \
	ETTemplateItemLayout.m \
	ETIconLayout.m \
	ETInstrument.m \
	ETSelectTool.m \
	ETPickDropCoordinator.m \
	ETInstruments.m \
	ETHandle.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
