include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = libEtoileUI

ADDITIONAL_OBJCFLAGS = 
libEtoileUI_OBJCFLAGS += -std=c99

libEtoileUI_OBJC_FILES = \
	Controls+Etoile.m \
	ETActionHandler.m \
	ETApplication.m \
	ETBasicItemStyle.m \
	ETBrowserLayout.m \
	ETColumnLayout.m \
	ETCompositeLayout.m \
	ETComputedLayout.m \
	ETController.m \
	ETContainer.m \
	ETDecoratorItem.m \
	ETEvent.m \
	ETFixedLayout.m \
	ETFlowLayout.m \
	ETFreeLayout.m \
	ETGeometry.m \
	ETInspector.m \
	ETLayer.m \
	ETLayoutItemBuilder.m \
	ETLayoutItem+Factory.m \
	ETLayoutItemGroup.m \
	ETLayoutItemGroup+Mutation.m \
	ETLayoutItem.m \
	ETLayoutItem+KVO.m \
	ETLayoutItem+Reflection.m \
	ETLayoutItem+Scrollable.m \
	ETLayoutItemFactory.m \
	ETLineFragment.m \
	ETLayout.m \
	ETLineLayout.m \
	ETModelDescriptionRenderer.m \
	ETNullLayout.m \
	ETObjectBrowserLayout.m \
	EtoileUIProperties.m \
	ETOutlineLayout.m \
	ETPaintBucketTool.m \
	ETPaneLayout.m \
	ETPersistencyController.m \
	ETPaintActionHandler.m \
	ETPickDropActionHandler.m \
	ETPickboard.m \
	ETScrollableAreaItem.m \
	ETSelectionAreaItem.m \
	ETShape.m \
	ETStyle.m \
	ETStyleGroup.m \
	ETTableLayout.m \
	ETTextEditorLayout.m \
	ETTitleBarItem.m \
	ETTitleBarView.m \
	ETUIItem.m \
	ETView.m \
	ETViewModelLayout.m \
	ETWidgetLayout.m \
	ETWindowItem.m \
	FSBrowserCell.m \
	NSCell+EtoileUI.m \
	NSImage+Etoile.m \
	NSObject+EtoileUI.m \
	NSView+Etoile.m \
	NSWindow+Etoile.m

libEtoileUI_OBJC_FILES += \
	UKPluginsRegistry+Icons.m \
	NSImage+NiceScaling.m \
	UKNibOwner.m

libEtoileUI_OBJC_FILES += \
	ETEventProcessor.m \
	ETTemplateItemLayout.m \
	ETIconLayout.m \
	ETTool.m \
	ETSelectTool.m \
	ETPickDropCoordinator.m \
	ETInstruments.m \
	ETHandle.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include GNUmakefile.postamble
